version: '3.8'

services:

  layoutlmv3-cuda-conda:
    image: layoutlmv3-cuda-conda:latest
    stdin_open: true
    tty: true
    volumes:
      - /home/carlitos/w210/w210-dev-personal:/user
    expose:
      - "8888"
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
